# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://Esukhia.github.io/bonltk//bonltk/"

git_url = "https://github.com/Esukhia/bonltk/tree/master/"

def custom_doc_links(name): return None
